import fs from 'node:fs';
import assert from 'node:assert/strict';
const model = fs.readFileSync(new URL('../client/src/PrototypeCurrentTwinModel.js', import.meta.url), 'utf8');
const cfg = fs.readFileSync(new URL('../client/src/ControlPolicyConfig.js', import.meta.url), 'utf8');
assert.match(model, /PROTOTYPE_CURRENT_REFERENCE_MAX_A/);
assert.match(model, /battery:\s*BATTERY_CONTROL_INTERNALS\.referenceMaxA/);
assert.match(cfg, /referenceMaxA:\s*1\.40/);
assert.match(model, /Math\.min\(1, prototypeCurrent \/ referenceMax\)/);
assert.match(model, /measuredCurrents\?\.c/);
console.log('prototype_current_live_twin_static_test: PASS');
